### ISSUE TITLE
how to create multiple users with this playbook?

### ISSUE THREAD

**Issue by aoyawale** [abaez/ansible-role-user#1]
Trying to figure out how to use this playbook to create all the users I need and adding their keys.

**Comment by abaez** [comment]
Hey @chagara,

I should've written more on this, but you can change the users by changing the variables listed in the map below:

``` yaml
users:
  main:
    name
    home
  super:
    name
    home
```

`users.super` would be for root all privilege user, whose only access is through rsa key. 
`users.main` would be for normal users, whose access is limited by the [template/main.j2](https://github.com/abaez/ansible-role-users/blob/master/templates/main.j2).

lastly, you can add your key inside the files directory to be added to the users.

**Comment by abaez** [comment]
Actually, after further inspection, I noticed that the key was hardwritten to be only `serve.pub` for access to the user. Changing this now in the coming up changesets.

**Comment by aoyawale** [comment]
thank you :) Just started learning ansible and this is one of the first tasked I need to complete.

**Comment by abaez** [comment]
I believe the readme is more approachable.  That and the fix to use of any pubkey should make this role manageable to your initial issue. Closing this stub. 

Lastly, welcome to the ansible love! Nothing like the ease of this tool to make life less straining.
