### ISSUE TITLE
how to run this playbook?

### ISSUE THREAD

**Issue by aoyawale** [abaez/ansible-role-user#2]
Helo,

Sorry to bother you again. I was wondering how to run this playbook. Do I use the travis.yml or run the other yml?

**Comment by abaez** [comment]
This isn't a playbook. It's only a role _for_ a playbook. You should read the [ansible documentation](http://docs.ansible.com/ansible/index.html) for more information on how to run a playbook and a role in a playbook, if that's what you looking for. This [role](http://docs.ansible.com/ansible/playbooks_roles.html) is only for user aggregation.
